/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mypersonalbudget.windows;
import com.bean.AddEntry;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import java.util.Date;
/**
 *
 * @author Krishna
 */
public class NewEntry extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewEntry() {
        initComponents();
        Date dNow = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-M-dd");
        String entryDate = ft.format(dNow);
        date.setText(entryDate);
        Double d = new SumOfMonth().getSumOfMonth();
        String sum = d.toString();
        sumOfThisMonth.setText(sum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headImage = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        itemName = new javax.swing.JTextField();
        itenNameLabel = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        itemDescriptionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        Submit = new javax.swing.JLabel();
        Clear = new javax.swing.JLabel();
        moneyspend = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        moneySpendBy = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        sumOfThisMonth = new javax.swing.JLabel();
        newEntryHeader = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        newEntry = new javax.swing.JMenuItem();
        home = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        editEntry = new javax.swing.JMenuItem();
        deleteEntry = new javax.swing.JMenuItem();
        View = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Entry");
        setBackground(new java.awt.Color(51, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));
        jPanel1.setLayout(null);

        headImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/head1 (2).jpg"))); // NOI18N
        headImage.setMaximumSize(new java.awt.Dimension(1100, 120));
        headImage.setPreferredSize(new java.awt.Dimension(1100, 120));
        jPanel1.add(headImage);
        headImage.setBounds(0, 0, 890, 120);

        costLabel.setFont(new java.awt.Font("Aller", 1, 18)); // NOI18N
        costLabel.setForeground(new java.awt.Color(255, 255, 255));
        costLabel.setText("Cost");
        jPanel1.add(costLabel);
        costLabel.setBounds(130, 250, 50, 23);
        jPanel1.add(itemName);
        itemName.setBounds(200, 210, 399, 30);

        itenNameLabel.setFont(new java.awt.Font("Aller", 1, 18)); // NOI18N
        itenNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        itenNameLabel.setText("Item Name");
        jPanel1.add(itenNameLabel);
        itenNameLabel.setBounds(80, 210, 100, 23);

        cost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                costKeyPressed(evt);
            }
        });
        jPanel1.add(cost);
        cost.setBounds(200, 250, 189, 30);

        dateLabel.setFont(new java.awt.Font("Aller", 1, 18)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("Date");
        jPanel1.add(dateLabel);
        dateLabel.setBounds(130, 290, 40, 23);
        jPanel1.add(date);
        date.setBounds(200, 290, 189, 30);

        itemDescriptionLabel.setFont(new java.awt.Font("Aller", 1, 18)); // NOI18N
        itemDescriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        itemDescriptionLabel.setText("Item Description");
        jPanel1.add(itemDescriptionLabel);
        itemDescriptionLabel.setBounds(30, 380, 150, 23);

        description.setColumns(20);
        description.setRows(5);
        description.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descriptionKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(description);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(200, 370, 399, 96);

        Submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Submit  button.png"))); // NOI18N
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        jPanel1.add(Submit);
        Submit.setBounds(200, 480, 111, 40);

        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear button.png"))); // NOI18N
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearMouseClicked(evt);
            }
        });
        jPanel1.add(Clear);
        Clear.setBounds(330, 480, 92, 40);

        moneyspend.setFont(new java.awt.Font("Aller", 1, 18)); // NOI18N
        moneyspend.setForeground(new java.awt.Color(255, 255, 255));
        moneyspend.setText("Money Spend By");
        jPanel1.add(moneyspend);
        moneyspend.setBounds(30, 330, 150, 23);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("This Month Total  :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 170, 168, 25);

        moneySpendBy.setEditable(true);
        moneySpendBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Krishna", "Mom", "Dad", "Other" }));
        moneySpendBy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                moneySpendByKeyPressed(evt);
            }
        });
        jPanel1.add(moneySpendBy);
        moneySpendBy.setBounds(200, 330, 189, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/New_Entry_Image.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(640, 150, 230, 360);

        sumOfThisMonth.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        sumOfThisMonth.setForeground(new java.awt.Color(204, 0, 0));
        sumOfThisMonth.setText("jLabel2");
        jPanel1.add(sumOfThisMonth);
        sumOfThisMonth.setBounds(410, 170, 180, 22);

        newEntryHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newEntryHeader.setForeground(new java.awt.Color(255, 255, 0));
        newEntryHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newEntryHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/light-blue-wallpaper-5.jpg"))); // NOI18N
        jPanel1.add(newEntryHeader);
        newEntryHeader.setBounds(0, 120, 890, 430);

        jMenuBar1.setBackground(new java.awt.Color(-14336,true));
        jMenuBar1.setAutoscrolls(true);
        jMenuBar1.setFont(new java.awt.Font("Dialog", 1, 18));

        File.setText("File");
        File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileActionPerformed(evt);
            }
        });

        newEntry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newEntry.setText("New Entry");
        newEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEntryActionPerformed(evt);
            }
        });
        File.add(newEntry);

        home.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        File.add(home);

        jMenuBar1.add(File);

        Edit.setText("Edit");

        editEntry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        editEntry.setText("Edit Entry");
        editEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEntryActionPerformed(evt);
            }
        });
        Edit.add(editEntry);

        deleteEntry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        deleteEntry.setText("Delete Entry");
        Edit.add(deleteEntry);

        jMenuBar1.add(Edit);

        View.setText("View");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("View");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        View.add(jMenuItem1);

        jMenuBar1.add(View);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        try{
        AddEntry addentry = new AddEntry();
        addentry.setItemName(itemName.getText());
        addentry.setItemCost(Double.parseDouble(cost.getText()));
        addentry.setDate(date.getText());
        addentry.setMoneySpendBy(moneySpendBy.getSelectedItem().toString());
        addentry.setItemDesc(description.getText());
        
        SessFactory sessfactory = new SessFactory();
        Session session = sessfactory.getSessionFactory().openSession();
        session.beginTransaction();
        session.save(addentry);
        session.getTransaction().commit();
        JOptionPane.showMessageDialog(this,"Saved Successfully.");
        session.close();
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(this,"Not Saved. Something entered wrong.");
        
        }
        Double d = new SumOfMonth().getSumOfMonth();
        sumOfThisMonth.setText(d.toString());
        ClearMouseClicked(evt);
        
    }//GEN-LAST:event_SubmitMouseClicked

    private void ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseClicked

        itemName.setText(null);
        cost.setText(null);
        Date dNow = new Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyyy-M-dd");
        String entryDate = ft.format(dNow);
        date.setText(entryDate);
        moneySpendBy.setSelectedItem("");
        description.setText("");
        
        
    }//GEN-LAST:event_ClearMouseClicked

    private void descriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descriptionKeyPressed
        
         if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            
             SubmitMouseClicked(null);
        }
        
        
    }//GEN-LAST:event_descriptionKeyPressed

    private void moneySpendByKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moneySpendByKeyPressed
        
         if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            
             SubmitMouseClicked(null);
        }
        
    }//GEN-LAST:event_moneySpendByKeyPressed

    private void costKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costKeyPressed
        
         if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            
             SubmitMouseClicked(null);
        }
        
    }//GEN-LAST:event_costKeyPressed

    private void newEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEntryActionPerformed

        this.dispose();
        NewEntry ne = new NewEntry();
        ne.setVisible(true);
    }//GEN-LAST:event_newEntryActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        this.dispose();
        HomePage  hm = new HomePage();
        hm.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileActionPerformed

    private void editEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEntryActionPerformed

        this.dispose();
        EditEntry ee = new EditEntry();
        ee.setVisible(true);
    }//GEN-LAST:event_editEntryActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        ViewFrame v = new ViewFrame();
        v.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clear;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu File;
    private javax.swing.JLabel Submit;
    private javax.swing.JMenu View;
    private javax.swing.JTextField cost;
    private javax.swing.JLabel costLabel;
    private javax.swing.JTextField date;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JMenuItem deleteEntry;
    private javax.swing.JTextArea description;
    private javax.swing.JMenuItem editEntry;
    private javax.swing.JLabel headImage;
    private javax.swing.JMenuItem home;
    private javax.swing.JLabel itemDescriptionLabel;
    private javax.swing.JTextField itemName;
    private javax.swing.JLabel itenNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox moneySpendBy;
    private javax.swing.JLabel moneyspend;
    private javax.swing.JMenuItem newEntry;
    private javax.swing.JLabel newEntryHeader;
    private javax.swing.JLabel sumOfThisMonth;
    // End of variables declaration//GEN-END:variables
}
